# 极客时间 - 程序员基础数学课 - [第39课 - 线性回归(上)高斯消元](https://time.geekbang.org/column/article/86014)



## 课后题

```
x1​ − 2*x2 ​+ x3 ​− 4*x4​ = 4
x2​ − x3 ​+ x4 ​= −3
x1​ + 3*x2 ​+ x4 = 1
−7*x2 ​+ 3*x3 ​+ x4 ​= −3
```

## 消元

In [133]:
import numpy as np

# 把方程组设定为增广矩阵
A = np.array([
    [1, -2,  1, -4,  4],
    [0,  1, -1,  1, -3],
    [1,  3,  0,  1,  1],
    [0, -7,  3,  1, -3]
])

print("增广矩阵:")
print(A)

增广矩阵:
[[ 1 -2  1 -4  4]
 [ 0  1 -1  1 -3]
 [ 1  3  0  1  1]
 [ 0 -7  3  1 -3]]


In [134]:
# 消除第3方程的x1
E1 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [-1, 0, 1, 0],
    [ 0, 0, 0, 1],
])

A1 = E1 @ A
print("消除第3方程的x1:")
print(A1)

消除第3方程的x1:
[[ 1 -2  1 -4  4]
 [ 0  1 -1  1 -3]
 [ 0  5 -1  5 -3]
 [ 0 -7  3  1 -3]]


In [135]:
# 消除第3方程的x2
E2 = np.array([
    [ 1,  0, 0, 0],
    [ 0,  1, 0, 0],
    [ 0, -5, 1, 0],
    [ 0,  0, 0, 1],
])

A2 = E2.dot(A1)
print("消除第3方程的x1:")
print(A2)

消除第3方程的x1:
[[ 1 -2  1 -4  4]
 [ 0  1 -1  1 -3]
 [ 0  0  4  0 12]
 [ 0 -7  3  1 -3]]


In [136]:
# 消除第4方程的x2
E3 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 7, 0, 1],
])

A3 = E3.dot(A2)
print("消除第4方程的x2:")
print(A3)

消除第4方程的x2:
[[  1  -2   1  -4   4]
 [  0   1  -1   1  -3]
 [  0   0   4   0  12]
 [  0   0  -4   8 -24]]


In [137]:
# 第3和第4方程互换形成上三角矩阵
E4 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 0, 1],
    [ 0, 0, 1, 0],
])

A4 = E4.dot(A3)
print("第3和第4方程互换形成上三角矩阵:")
print(A4)

第3和第4方程互换形成上三角矩阵:
[[  1  -2   1  -4   4]
 [  0   1  -1   1  -3]
 [  0   0  -4   8 -24]
 [  0   0   4   0  12]]


In [138]:
# 消除第三方程的x3
E5 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 0, 1, 1],
])

A5 = E5.dot(A4)
print("消除第4方程的x3:")
print(A5)

消除第4方程的x3:
[[  1  -2   1  -4   4]
 [  0   1  -1   1  -3]
 [  0   0  -4   8 -24]
 [  0   0   0   8 -12]]


In [139]:
# 得到消元矩阵E
E = E5 @ E4 @ E3 @ E2 @ E1
print("得到消元矩阵E:")
print(E)

# 直接运用消元矩阵E
print("E 乘以 增广矩阵A 得到上三角矩阵:")
print(E @ A)

得到消元矩阵E:
[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  7  0  1]
 [-1  2  1  1]]
E 乘以 增广矩阵A 得到上三角矩阵:
[[  1  -2   1  -4   4]
 [  0   1  -1   1  -3]
 [  0   0  -4   8 -24]
 [  0   0   0   8 -12]]


## 回代

In [140]:
# A5是最终的上三角矩阵
print("A5是最终的上三角矩阵")
print(A5)

# 把第4方程的x4系数除以8
S1 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 0, 0, 1/8],
])
B1 = S1 @ A5
print("把第4方程的x4系数除以8")
print(B1)

A5是最终的上三角矩阵
[[  1  -2   1  -4   4]
 [  0   1  -1   1  -3]
 [  0   0  -4   8 -24]
 [  0   0   0   8 -12]]
把第4方程的x4系数除以8
[[  1.   -2.    1.   -4.    4. ]
 [  0.    1.   -1.    1.   -3. ]
 [  0.    0.   -4.    8.  -24. ]
 [  0.    0.    0.    1.   -1.5]]


In [148]:
# 把第3方程的x3系数变为1，就是除以-4
S2 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, -1/4, 0],
    [ 0, 0, 0, 1],
])
B2 = S2 @ B1
print("把第3方程的x3系数变为1，就是除以-4")
print(B2)

把第3方程的x3系数变为1，就是除以-4
[[ 1.  -2.   1.  -4.   4. ]
 [ 0.   1.  -1.   1.  -3. ]
 [ 0.   0.   1.  -2.   6. ]
 [ 0.   0.   0.   1.  -1.5]]
把第3方程的x4减掉，就是第3方程 + (2 * 第4方程)
[[ 1.  -2.   1.  -4.   4. ]
 [ 0.   1.  -1.   1.  -3. ]
 [ 0.   0.   1.   0.   3. ]
 [ 0.   0.   0.   1.  -1.5]]


In [ ]:
# 把第3方程的x4减掉，就是第3方程 + (2 * 第4方程)
S3 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 2],
    [ 0, 0, 0, 1],
])
B3 = S3 @ B2
print("把第3方程的x4减掉，就是第3方程 + (2 * 第4方程)")
print(B3)


In [142]:
# 把第2方程的x3减掉，就是第2方程 + 第3方程
# 把第2方程的x4减掉，就是第2方程 + (-1 * 第4方程)
S4 = np.array([
    [ 1, 0, 0, 0],
    [ 0, 1, 1, -1],
    [ 0, 0, 1, 0],
    [ 0, 0, 0, 1],
])
B4 = S4 @ B3
print("把第2方程的x3减掉，就是第2方程 + 第3方程")
print("把第2方程的x4减掉，就是第2方程 + (-1 * 第4方程)")
print(B4)

把第2方程的x3减掉，就是第2方程 + 第3方程
把第2方程的x4减掉，就是第2方程 + (-1 * 第4方程)
[[ 1.  -2.   1.  -4.   4. ]
 [ 0.   1.   0.   0.   1.5]
 [ 0.   0.   1.   0.   3. ]
 [ 0.   0.   0.   1.  -1.5]]


In [143]:
# 把第1方程的x2减掉，就是第1方程 + (2 * 第2方程)
# 把第1方程的x3减掉，就是第1方程 + (-1 * 第3方程)
# 把第1方程的x4减掉，就是第1方程 + (4 * 第4方程)
S5 = np.array([
    [ 1, 2, -1, 4],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 0, 0, 1],
])
B5 = S5 @ B4
print("把第1方程的x2减掉，就是第1方程 + (2 * 第2方程)")
print("把第1方程的x3减掉，就是第1方程 + (-1 * 第3方程)")
print("把第1方程的x4减掉，就是第1方程 + (4 * 第4方程)")
print(B5)

print("可以看到增广矩阵A左侧已经变成单元矩阵了")


把第1方程的x2减掉，就是第1方程 + (2 * 第2方程)
把第1方程的x3减掉，就是第1方程 + (-1 * 第3方程)
把第1方程的x4减掉，就是第1方程 + (4 * 第4方程)
[[ 1.   0.   0.   0.  -2. ]
 [ 0.   1.   0.   0.   1.5]
 [ 0.   0.   1.   0.   3. ]
 [ 0.   0.   0.   1.  -1.5]]
可以看到增广矩阵A左侧已经变成单元矩阵了


In [144]:
# 得到SE矩阵
SE = S5 @ S4 @ S3 @ S2 @ S1 @ E
print("SE矩阵:")
print(SE)

# 系数矩阵
X = np.delete(A, len(A[0])-1, axis=1)
print("系数矩阵:")
print(X)

# SE 乘以 系数矩阵
print("SE 乘以 系数矩阵得到单位矩阵:")
print(SE @ X)

# SE 乘以 A
print("SE 乘以 增广矩阵A:")
print(SE @ A)

SE矩阵:
[[ 0.5    1.25   0.5    0.25 ]
 [-0.125 -0.5    0.125 -0.125]
 [-0.25  -1.25   0.25   0.   ]
 [-0.125  0.25   0.125  0.125]]
系数矩阵:
[[ 1 -2  1 -4]
 [ 0  1 -1  1]
 [ 1  3  0  1]
 [ 0 -7  3  1]]
SE 乘以 系数矩阵得到单位矩阵:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
SE 乘以 增广矩阵A:
[[ 1.   0.   0.   0.  -2. ]
 [ 0.   1.   0.   0.   1.5]
 [ 0.   0.   1.   0.   3. ]
 [ 0.   0.   0.   1.  -1.5]]


In [145]:
# 得到的结果就是单元矩阵
B=B5
print("结果:")
print("x1 =", B[0][4])
print("x2 =", B[1][4])
print("x3 =", B[2][4])
print("x4 =", B[3][4])

结果:
x1 = -2.0
x2 = 1.5
x3 = 3.0
x4 = -1.5
